scalar Affordances

"""
Implement the DateTime<Utc> scalar

The input/output is a string in RFC3339 format.
"""
scalar DateTime

"""
A scalar that can represent any JSON value.
"""
scalar JSON

enum Lane {
	ACCUMULATED
	PRESENCE
}

type LanesPaused {
	lanes: [Lane!]!
}

type LanesResumed {
	lanes: [Lane!]!
}

type MutationAck {
	success: Boolean!
}

"""
A UUID is a unique 128-bit number, stored as 16 octets. UUIDs are parsed as
Strings within GraphQL. UUIDs are used to assign unique identifiers to
entities without requiring a central allocating authority.

# References

* [Wikipedia: Universally Unique Identifier](http://en.wikipedia.org/wiki/Universally_unique_identifier)
* [RFC4122: A Universally Unique Identifier (UUID) URN Namespace](http://tools.ietf.org/html/rfc4122)
"""
scalar UUID

union WorkspaceDelta = WorkspaceReset | WorkspaceUpsert | WorkspaceRemove | LanesPaused | LanesResumed

type WorkspaceMutation {
	workspaceCreate(id: UUID!, name: String!): MutationAck!
	workspaceDelete(id: UUID!): MutationAck!
	workspaceTransfer(id: UUID!, to: UUID!): MutationAck!
	workspaceProtectFile(fileId: UUID!, protected: Boolean!): MutationAck!
	workspaceAnnotateFile(fileId: UUID!, metadata: JSON!): MutationAck!
}

type WorkspaceQuery {
	workspaceWorkspace(id: UUID!): WorkspaceView
	workspaceWorkspaces: [WorkspaceView!]!
}

type WorkspaceRemove {
	revision: Int!
	projector: String!
	key: JSON!
	cause: JSON
}

type WorkspaceReset {
	revision: Int!
	views: [WorkspaceViewUnion!]!
}

type WorkspaceSubscription {
	workspaceDeltas: WorkspaceDelta!
}

type WorkspaceUpsert {
	revision: Int!
	view: WorkspaceViewUnion!
	cause: JSON
}

type WorkspaceView {
	id: UUID!
	name: String!
	ownerId: UUID!
	createdAt: DateTime!
	affordances: Affordances!
}

union WorkspaceViewUnion = WorkspaceView

"""
Directs the executor to include this field or fragment only when the `if` argument is true.
"""
directive @include(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Directs the executor to skip this field or fragment when the `if` argument is true.
"""
directive @skip(if: Boolean!) on FIELD | FRAGMENT_SPREAD | INLINE_FRAGMENT
"""
Provides a scalar specification URL for specifying the behavior of custom scalar types.
"""
directive @specifiedBy(url: String!) on SCALAR
schema {
	query: WorkspaceQuery
	mutation: WorkspaceMutation
	subscription: WorkspaceSubscription
}
